name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: erlef/setup-beam@v1
        with:
          gleam-version: "1.16.0"
          otp-version: false
      - run: bun install
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
